<a href="https://colab.research.google.com/github/diego-burgos/PracticaNumpy/blob/main/PracticaNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import numpy as np

# Paso 1: Creación de Arrays
# o Crea un array unidimensional (vector) con 5 elementos enteros de tu elección.
vector = np.array([10, 20, 30, 40, 50])
print("Vector:", vector)
print("___________________________________________________________\n")

# o Crea una matriz bidimensional (matriz) de tamaño 3x3 con valores enteros consecutivos.
matriz_consecutiva = np.arange(1, 10).reshape(3, 3)
print("Matriz consecutiva:\n", matriz_consecutiva)
print("___________________________________________________________\n")

# o Utiliza la función np.zeros() para crear una matriz de tamaño 2x4 llena de ceros.
matriz_zeros = np.zeros((2, 4))
print("Matriz de ceros:\n", matriz_zeros)
print("___________________________________________________________\n")

# o Utiliza la función np.ones() para crear una matriz de tamaño 3x2 llena de unos.
matriz_ones = np.ones((3, 2))
print("Matriz de unos:\n", matriz_ones)
print("___________________________________________________________\n")

# o Utiliza la función np.random.randint() para crear una matriz de tamaño 4x4 con números enteros aleatorios entre 0 y 10.
matriz_aleatoria = np.random.randint(0, 11, (4, 4))
print("Matriz aleatoria:\n", matriz_aleatoria)

Vector: [10 20 30 40 50]
___________________________________________________________

Matriz consecutiva:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
___________________________________________________________

Matriz de ceros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
___________________________________________________________

Matriz de unos:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
___________________________________________________________

Matriz aleatoria:
 [[ 5  0  3  3]
 [ 2  9  7  8]
 [ 9  1  3  6]
 [ 0  1 10  1]]


In [32]:
# Paso 2: Acceso a Elementos
# o Accede al tercer elemento del vector creado en el paso 1.
tercer_elemento_vector = vector[2]
print("Tercer elemento del vector:", tercer_elemento_vector)
print("___________________________________________________________\n")

# o Accede al elemento en la segunda fila y segunda columna de la matriz creada en el paso 1.
elemento_segunda_fila_segunda_columna = matriz_consecutiva[1, 1]
print("Elemento en la segunda fila y segunda columna de la matriz consecutiva es:", elemento_segunda_fila_segunda_columna)

Tercer elemento del vector: 30
___________________________________________________________

Elemento en la segunda fila y segunda columna de la matriz: 5


In [33]:
# Paso 3: Propiedades de los Arrays
# o Utiliza el atributo ndim para verificar la cantidad de dimensiones de la matriz creada en el paso 2.
dimensiones_matriz = matriz_consecutiva.ndim
print("Cantidad de dimensiones de la matriz:", dimensiones_matriz)
print("___________________________________________________________\n")

# o Utiliza el atributo shape para obtener la forma de la matriz creada en el paso 2.
forma_matriz = matriz_consecutiva.shape
print("Forma de la matriz:", forma_matriz)
print("___________________________________________________________\n")

# o Utiliza el atributo size para obtener el tamaño total de la matriz creada en el paso 2.
tamaño_matriz = matriz_consecutiva.size
print("Tamaño total de la matriz:", tamaño_matriz)
print("___________________________________________________________\n")

Cantidad de dimensiones de la matriz: 2
___________________________________________________________

Forma de la matriz: (3, 3)
___________________________________________________________

Tamaño total de la matriz: 9
___________________________________________________________



In [37]:
# Paso 4: Operaciones Básicas
# o Suma dos matrices de tamaño 2x2 con valores aleatorios entre 0 y 10.
matriz_sum_altr1 = np.random.randint(0, 11, (2, 2))
matriz_sum_altr2 = np.random.randint(0, 11, (2, 2))
suma_matrices = matriz_sum_altr1 + matriz_sum_altr2
print("Matriz de tamañano 2x2:\n", matriz_sum_altr1)
print("Matriz de tamañano 2x2:\n", matriz_sum_altr2)
print("Suma de matrices aleatorias:\n", suma_matrices, "\n")
print("___________________________________________________________\n")

# o Multiplica dos matrices de tamaño 3x2 y 2x3 respectivamente.
matriz_multiplicacion1 = np.random.randint(0, 11, (3, 2))
matriz_multiplicacion2 = np.random.randint(0, 11, (2, 3))
producto_matrices = np.dot(matriz_multiplicacion1, matriz_multiplicacion2)
print("Matriz de tamañano 3x2:\n", matriz_multiplicacion1)
print("Matriz de tamañano 2x3:\n", matriz_multiplicacion2)
print("Producto de matrices:\n", producto_matrices, "\n")
print("___________________________________________________________\n")

# o Divide una matriz de tamaño 2x2 por otra matriz de tamaño 2x2, utilizando tanto la división por elementos como la multiplicación por la inversa.
matriz_A = np.random.randint(1, 11, (2, 2))
matriz_B = np.random.randint(1, 11, (2, 2))
division_elementos = matriz_A / matriz_B
multiplicacion_inversa = np.dot(matriz_A, np.linalg.inv(matriz_B))
print("Matriz de tamañano 2x2:\n", matriz_A)
print("Matriz de tamañano 2x2:\n", matriz_B)
print("División por elementos:\n", division_elementos)
print("Multiplicación por la inversa:\n", multiplicacion_inversa)

Matriz de tamañano 2x2:
 [[6 9]
 [1 1]]
Matriz de tamañano 2x2:
 [[6 5]
 [4 2]]
Suma de matrices aleatorias:
 [[12 14]
 [ 5  3]] 

___________________________________________________________

Matriz de tamañano 3x2:
 [[ 5  9]
 [10  3]
 [10  6]]
Matriz de tamañano 2x3:
 [[ 3  0  5]
 [ 7  0 10]]
Producto de matrices:
 [[ 78   0 115]
 [ 51   0  80]
 [ 72   0 110]] 

___________________________________________________________

Matriz de tamañano 2x2:
 [[1 8]
 [7 2]]
Matriz de tamañano 2x2:
 [[ 7  6]
 [10  1]]
División por elementos:
 [[0.14285714 1.33333333]
 [0.7        2.        ]]
Multiplicación por la inversa:
 [[ 1.49056604 -0.94339623]
 [ 0.24528302  0.52830189]]


In [39]:
# Paso 5: Manipulación de Arrays
# o Utiliza la función reshape() para convertir el vector creado en el paso 1 en una matriz de tamaño 9x1.
matriz_2x3 = matriz_consecutiva.reshape(9, 1)
print("Matriz 2x3:\n", matriz_2x3)
print("___________________________________________________________\n")

# o Utiliza la función flatten() para convertir la matriz creada en el paso 1 en un vector unidimensional.
vector_flatten = matriz_consecutiva.flatten()
print("Vector flatten:", vector_flatten)

Matriz 2x3:
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
___________________________________________________________

Vector flatten: [1 2 3 4 5 6 7 8 9]


In [40]:
# Paso 6: Operaciones Estadísticas
# o Calcula la suma de todos los elementos de la matriz creada en el paso 1.
suma_total_matriz = np.sum(matriz_consecutiva)
print("Suma total de la matriz:", suma_total_matriz)
print("___________________________________________________________\n")

# o Calcula la media de cada fila de la matriz creada en el paso 1.
media_filas_matriz = np.mean(matriz_consecutiva, axis=1)
print("Media de cada fila de la matriz:\n", media_filas_matriz)

Suma total de la matriz: 45
___________________________________________________________

Media de cada fila de la matriz:
 [2. 5. 8.]


In [42]:
# Paso 7: Indexación y Rebanado
# o Imprime la primera fila de la matriz creada en el paso 1.
primera_fila_matriz = matriz_consecutiva[0]
print("Primera fila de la matriz:\n", primera_fila_matriz)
print("___________________________________________________________\n")

# o Imprime las primeras dos columnas de la matriz creada en el paso 1.
primeras_dos_columnas_matriz = matriz_consecutiva[:, :2]
print("Primeras dos columnas de la matriz:\n", primeras_dos_columnas_matriz)

Primera fila de la matriz:
 [1 2 3]
___________________________________________________________

Primeras dos columnas de la matriz:
 [[1 2]
 [4 5]
 [7 8]]


In [24]:
# Paso 8: Ejercicio Adicional
# o Define una matriz de tamaño 4x4 con valores aleatorios.
matriz_aleatoria_adicional = np.random.randint(0, 101, (4, 4))
print("Matriz aleatoria adicional:\n", matriz_aleatoria_adicional)

Matriz aleatoria adicional:
 [[ 32  90  54  42]
 [ 43  77  66  64]
 [100  32  56   1]
 [ 95  11  80  94]]


In [43]:
# o Escribe un código para encontrar el valor máximo y mínimo de la matriz, así como su posición.
valor_maximo = np.max(matriz_aleatoria_adicional)
valor_minimo = np.min(matriz_aleatoria_adicional)
posicion_maximo = np.unravel_index(np.argmax(matriz_aleatoria_adicional), matriz_aleatoria_adicional.shape)
posicion_minimo = np.unravel_index(np.argmin(matriz_aleatoria_adicional), matriz_aleatoria_adicional.shape)
print("Valor máximo:", valor_maximo, "en la posición:", posicion_maximo)
print("___________________________________________________________\n")
print("Valor mínimo:", valor_minimo, "en la posición:", posicion_minimo)

Valor máximo: 100 en la posición: (2, 0)
___________________________________________________________

Valor mínimo: 1 en la posición: (2, 3)
